;public & external symbols

                extrn   n_calc:near
                extrn   sqrt:near
                extrn   rotate_shape:near
                extrn   rotate_normals:near
                extrn   prep_sort:near
                extrn   sort:near

                extrn   shape_addr:dword
                extrn   srot_addr:dword
                extrn   n_addr:dword
                extrn   nrot_addr:dword
                extrn   inc_addr:dword
                extrn   con_addr:dword
                extrn   sort_addr:dword
                extrn   points:dword
                extrn   faces:dword

                extrn   r_x:word
                extrn   r_y:word
                extrn   r_z:word